[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "{{ pillar["homu"]["gh-access-token"] }}"

# A GitHub oauth application for this instance of homu:
app_client_id = "{{ pillar["homu"]["app-client-id"] }}"
app_client_secret = "{{ pillar["homu"]["app-client-secret"] }}"

[web]

# The port homu listens on
port = 54856

# An example configuration for repository (there can be many of these)
[repo.servo]

# github.com/<owner>/<name>
owner = "servo"
name = "servo"

# who has r+ rights?
reviewers = ["glennw","jdm","kmcallister","larsbergstrom","Manishearth","metajack","mbrubeck","Ms2ger","pcwalton","SimonSapin","mrobinson","brunoabinader","saneyuki"]

## branch names (these settings here are the defaults)
#[repo.NAME.branch]
#
#master = "master"
#auto = "auto"
#try = "try"
#tmp = "tmp"
#rollup = "rollup"

[repo.servo.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

## Use buildbot for running tests
[repo.servo.buildbot]

url = "http://build.servo.org"
secret = "{{ pillar["homu"]["buildbot-secret"] }}"

builders = ["linux1", "linux2", "linux3", "android", "mac1", "mac2", "gonk"]
try_builders = ["linux1", "linux2", "linux3", "android", "mac1", "mac2", "gonk"]

#
username = "{{ pillar["homu"]["buildbot-http-user"] }}"
password = "{{ pillar["homu"]["buildbot-http-pass"] }}"

## Use travis for running tests
#[repo.NAME.travis]
#
## found under <https://travis-ci.org/profile/info>.
#token = ""
