[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "{{ pillar["homu"]["gh-access-token"] }}"

# A GitHub oauth application for this instance of homu:
app_client_id = "{{ pillar["homu"]["app-client-id"] }}"
app_client_secret = "{{ pillar["homu"]["app-client-secret"] }}"

[web]
port = 54856

{% set repos = [('servo', 'html5ever'), ('servo', 'euclid'), ('servo', 'rust-layers'),
                ('servo', 'saltfs'), ('servo', 'gleam'), ('servo', 'string-cache'),
                ('servo', 'rust-selectors'), ('servo', 'rust-azure'), ('servo', 'tendril'),
                ('servo', 'futf'), ('servo', 'glutin')] %}
{% set reviewers = ["glennw","jdm","kmcallister","larsbergstrom","Manishearth","metajack","mbrubeck","Ms2ger","pcwalton","SimonSapin","mrobinson","brunoabinader","saneyuki","nox"] %}

[repo.servo]
owner = "servo"
name = "servo"
reviewers = {{ reviewers }}

[repo.servo.github]
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

[repo.servo.buildbot]
url = "http://build.servo.org"
secret = "{{ pillar["homu"]["buildbot-secret"] }}"
builders = ["linux1", "linux2", "linux3", "android", "mac1", "mac2", "mac3", "gonk"]
try_builders = ["linux1", "linux2", "linux3", "android", "mac1", "mac2", "mac3", "gonk"]
username = "{{ pillar["homu"]["buildbot-http-user"] }}"
password = "{{ pillar["homu"]["buildbot-http-pass"] }}"

{% for repo in repos %}
[repo.{{ repo[1] }}]
owner = "{{ repo[0] }}"
name = "{{ repo[1] }}"
reviewers = {{ reviewers }}

[repo.{{ repo[1] }}.github]
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

[repo.{{ repo[1] }}.travis]
token = "{{ pillar["homu"]["travis-ci-token"] }}"

{% endfor %}
